# Generated by Django 3.2 on 2021-05-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAsociacionAgencia',
            fields=[
                ('IdS', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('Nombre de la agencia', models.CharField(max_length=50)),
                ('Direccón principal', models.CharField(max_length=120)),
                ('email agencia', models.EmailField(max_length=254)),
                ('Fax', models.CharField(max_length=20)),
                ('Entidad bancaria de respaldo', models.CharField(max_length=80)),
                ('Años de antigüedad', models.PositiveIntegerField()),
                ('Manager nombre', models.CharField(max_length=70)),
                ('email manager', models.EmailField(max_length=254)),
                ('Pespectiva', models.PositiveIntegerField(verbose_name='Cuánto tiempo espera trabajar con nosotros?')),
            ],
        ),
    ]
