# Generated by Django 3.2 on 2021-05-22 13:42

import agencias.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacionindividual',
            old_name='cantidadAcompansantes',
            new_name='cantidadAcompanhantes',
        ),
        migrations.RemoveField(
            model_name='reservacionpaquete',
            name='companiaAereaRP',
        ),
        migrations.AddField(
            model_name='reservacionpaquete',
            name='companiaAerea',
            field=agencias.fields.FlyCompanyModelField(choices=[('1', 'Iberia'), ('2', 'Air Dream'), ('3', 'Fly Eminem'), ('4', 'Astro Drum'), ('5', 'Aerolineas Continental'), ('6', 'Americans Air Dream'), ('7', 'Fly ForFly')], default=1, max_length=1, verbose_name='Compañía Aérea'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='IdA',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='IdA'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='excursiones',
            field=models.ManyToManyField(blank=True, to='agencias.Excursion'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='hoteles',
            field=models.ManyToManyField(blank=True, to='agencias.Hotel'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='diaLlegada',
            field=agencias.fields.DayWeekField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=1, verbose_name='Día de Llegada'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='diaSalida',
            field=agencias.fields.DayWeekField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('7', 'Domingo')], max_length=1, verbose_name='Día de Salida'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='hoteles',
            field=models.ManyToManyField(blank=True, to='agencias.Hotel'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencias.agencia', verbose_name='Agencia'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='facilidades',
            field=models.ManyToManyField(blank=True, to='agencias.Facilidad'),
        ),
        migrations.AlterField(
            model_name='reservacionindividual',
            name='companiaAerea',
            field=agencias.fields.FlyCompanyModelField(choices=[('1', 'Iberia'), ('2', 'Air Dream'), ('3', 'Fly Eminem'), ('4', 'Astro Drum'), ('5', 'Aerolineas Continental'), ('6', 'Americans Air Dream'), ('7', 'Fly ForFly')], default=1, max_length=1, verbose_name='Compañía Aérea'),
        ),
    ]
