# Generated by Django 3.2 on 2021-05-27 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencias', '0002_auto_20210522_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacionhotel',
            name='fechaLlegada',
            field=models.DateField(default=datetime.date(2021, 5, 27), verbose_name='Fecha Llegada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacionhotel',
            name='fechaSalida',
            field=models.DateField(default=datetime.date(2021, 5, 27), verbose_name='Fecha Salida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacionindividual',
            name='hoteles',
            field=models.ManyToManyField(editable=False, through='agencias.ReservacionHotel', to='agencias.Hotel'),
        ),
    ]
