# Generated by Django 3.2 on 2021-05-28 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencias', '0003_auto_20210527_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacionhotel',
            old_name='IdH',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='reservacionhotel',
            old_name='IdRI',
            new_name='reservacion',
        ),
    ]
