# Generated by Django 3.2 on 2021-05-31 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencias', '0004_auto_20210527_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='categoria',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='turista',
            name='tipo',
            field=models.CharField(choices=[('I', 'Individual'), ('P', 'Paquete'), ('M', 'Mixto')], max_length=2),
        ),
    ]
